### ISSUE TITLE
AWS Elasticache

### ISSUE THREAD

**Issue by seahawks8** [pinterest/pymemcache#277] opened 2020-04-07 05:32 UTC
I wanted to run this by you all first before I setup create the branch and submit the pull-request.
I will implement the following
- add a Elasticache flag to the HashClient
   - dynamically identify the nodes and set them accordingly.
   - add the Jenkins hashing function - Elasticache uses Jenkins by Default, but they also make murmur3 available

Perhaps it would make more sense to inherit from the HashClient Class and create a new one called "ElasticacheClient".

What are your thoughts?

**Comment by jparise** [comment] 2020-04-07 15:38
I think I prefer the separate `ElasticacheClient` approach.

**Comment by jparise** [comment] 2021-06-16 14:29
I'm closing this given that the issue is primarily a question and the next step would be to discuss a proposed pull request.

**Closed by jparise** 2021-06-16 14:29 UTC
Labels: enhancement, question
