### ISSUE TITLE
KeyError when no connections are available using HashClient

### ISSUE THREAD

**Issue by renstrom** [pinterest/pymemcache#77] opened 2015-08-19 09:26 UTC
When the `HashClient` runs out connections it will start raising `KeyError` (even with `ignore_exc=True`). Reproduce with this:

```python
>>> from pymemcache.client.hash import HashClient
>>> client = HashClient([('localhost', 11211)], use_pooling=True, ignore_exc=True,
...                     timeout=2, connect_timeout=2)
>>> client.set('foo', 'bar')
True
>>> client.get('foo')
'bar'
>>> # Stop Memcached server
...
>>> client.get('foo')
>>> client.get('foo')
>>> client.get('foo')
>>> client.get('foo')
>>> client.get('foo')
>>> client.get('foo')
>>> client.get('foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Peter/.vim/venv/lib/python2.7/site-packages/pymemcache/client/hash.py", line 226, in get
    return self._run_cmd('get', key, None, *args, **kwargs)
  File "/Users/Peter/.vim/venv/lib/python2.7/site-packages/pymemcache/client/hash.py", line 214, in _run_cmd
    client = self._get_client(key)
  File "/Users/Peter/.vim/venv/lib/python2.7/site-packages/pymemcache/client/hash.py", line 134, in _get_client
    client = self.clients[server]
KeyError: None
```

**Comment by cgordon** [comment] 2015-09-02 23:52
@sontek 

I took a look at the code. This is caused by the _get_client method in HashClient returning None when there are no live nodes. Fixing that is going to require a little bit of code restructuring, since there isn't a good way to return a correct value from the place the error occurs. I'll have time for this next week, adding John Anderson in case he has time sooner.

**Comment by sontek** [comment] 2015-09-02 23:53
Thanks for poking me, I didn't notice this error report. I'll fix it up tonight

**Comment by sontek** [comment] 2015-09-06 16:12
@cgordon @renstrom Sorry I got busy the other night but #81 will make it graceful when ignore exceptions are set.

**Comment by cgordon** [comment] 2015-09-10 16:07
Will close this when it is deployed to pypi (this weekend).

**Closed** 2016-03-18 17:31 UTC
