### ISSUE TITLE
socket.error: [Errno 2] No such file or directory when connecting over localhost on Python 2.7

### ISSUE THREAD

**Issue by metigue** [pinterest/pymemcache#416] opened 2022-08-22 10:31 UTC
Hi there,

I'm having an issue where I get a socket error when connecting over localhost - I've tested connecting to an external server and that was working fine.

My code is as follows:

```python
from pymemcache.client.base import PooledClient
from pymemcache import serde

MEMCACHE = PooledClient('127.0.0.1', max_pool_size=10, connect_timeout=5, timeout=10, serde=serde.PickleSerde(pickle_version=2))

MEMCACHE.set('test', 'a')
```

And the traceback is:

```
Traceback (most recent call last):
  File "test_memcache.py", line 6, in <module>
    MEMCACHE.set('test', 'a')
  File "/home/work/.local/lib/python2.7/site-packages/pymemcache/client/base.py", line 1081, in set
    flags=flags)
  File "/home/work/.local/lib/python2.7/site-packages/pymemcache/client/base.py", line 341, in set
    flags=flags)[key]
  File "/home/work/.local/lib/python2.7/site-packages/pymemcache/client/base.py", line 930, in _store_cmd
    self._connect()
  File "/home/work/.local/lib/python2.7/site-packages/pymemcache/client/base.py", line 296, in _connect
    sock.connect(self.server)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory
```

Memcached is running and I can telnet to it over 127.0.0.1 fine so I'm really not sure what the issue is.

**Comment by jogo** [comment] 2022-08-22 16:19
I tried to reproduce the issue with python2.7 and the latest version of pymemcache and am unable to reproduce the issue when memcached is running.

**Comment by jogo** [comment] 2022-09-12 16:51
Closing as cannot reproduce , if you have a consistent way to reproduce please re-open.

**Closed by jogo** 2022-09-12 16:51 UTC
